# Generated by Django 6.0.6 on 2026-06-23 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=15)),
                ('document', models.FileField(upload_to='orders/documents/')),
                ('copies', models.PositiveIntegerField(default=1)),
                ('print_type', models.CharField(choices=[('bw', 'Black & White'), ('color', 'Color')], default='bw', max_length=20)),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('Letter', 'Letter')], default='A4', max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
