# Generated by Django 6.0.6 on 2026-06-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pay_at_shop', 'Pay at Shop'), ('online', 'Online Payment')], default='pay_at_shop', max_length=20),
        ),
    ]
